
services:
  caddy:
    image: docker.io/technoguyfication/caddy-cloudflare:latest@sha256:6cfa5a71663247d10d99342824044c9dc1db5265d4504b3615e129db7a0f77e4
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - MY_DOMAIN
      - CLOUDFLARE_API_TOKEN
      - ACME_AGREE=true
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_config:/config
      - ./caddy_data:/data

networks:
  default:
    name: caddy_proxy
    external: true
