
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:2.18.02
    container_name: tdarr
    restart: unless-stopped
    networks:
      - caddy_proxy
    ports:
      - 8265:8265 
      - 8266:8266 
    environment:
      - TZ=Europe/London
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      # - ffmpegVersion=6
      - nodeName=InternalNode
    volumes:
      - ./server:/app/server
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./media:/media
      - ./transcode_cache:/temp
      - ${STORAGE_PATH}:/mnt/storage

    devices:
      - /dev/dri:/dev/dri
    
networks:
  caddy_proxy:
    external: true
