services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.9.4@sha256:3e6710a7ab2a61311d9d899b719f6c3657791c63e8f4942cec4ebc42401d6b76
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/London
    volumes:
      - homeassistant_data:/config

volumes:
  homeassistant_data:
    name: homeassistant_data
    external: true
