services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.7.3@sha256:6937c6c51d2f5d6aa66d97e4a68f845bcccd5f9b62cd91992bd6d79b20fe2b3c
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/London
    volumes:
      - homeassistant_data:/config

volumes:
  homeassistant_data:
    name: homeassistant_data
    external: true
