services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2025.6.1@sha256:857745bd01589750174e60f2c477a65da1169c4f1c098a58db792baae7f7ada6
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/London
    volumes:
      - homeassistant_data:/config

volumes:
  homeassistant_data:
    name: homeassistant_data
    external: true
