services:  
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.0@sha256:5bb66eac5d48f021fd60414add03aa123d1feb85770550ddb1d99a5b8851c6c2
    container_name: homepage
    restart: unless-stopped
    networks:
      - caddy_proxy
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ${DATA_PATH}:/mnt/data
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
        HOMEPAGE_ALLOWED_HOSTS: internal.ajanthank.com

networks:
  caddy_proxy:
    external: true
