services:  
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
    container_name: homepage
    restart: unless-stopped
    networks:
      - caddy_proxy
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ${DATA_PATH}:/mnt/data
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
        HOMEPAGE_ALLOWED_HOSTS: internal.ajanthank.com

networks:
  caddy_proxy:
    external: true
