services:  
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.0@sha256:690ac1f79e33000c176c2a28229ed00b49b44781e8a63f280a8ece22c161f099
    container_name: homepage
    restart: unless-stopped
    networks:
      - caddy_proxy
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ${DATA_PATH}:/mnt/data
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
        HOMEPAGE_ALLOWED_HOSTS: internal.ajanthank.com

networks:
  caddy_proxy:
    external: true
