---
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./redisdata:/data

  db:
    image: docker.io/library/postgres:17@sha256:29e0bb09c8e7e7fc265ea9f4367de9622e55bae6b0b97e7cce740c2d63c2ebc0
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.18.0@sha256:13ef2894816c68672367acb75e896d8eb2ab8057e5059d39ae93f80d49ab8725
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
    networks:
      - caddy_proxy
      - default
    ports:
      - 8010:8000
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: ${USER_PUID}
      USERMAP_GID: ${USER_PGID}
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_LANGUAGES: eng kor
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_URL: ${PAPERLESS_URL}
    volumes:
      - ${STORAGE_PATH}/paperless/export:/usr/src/paperless/export
      - ${STORAGE_PATH}/paperless/consume:/usr/src/paperless/consume
      - ./data:/usr/src/paperless/data
      - ./paperless/media:/usr/src/paperless/media

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    networks:
      - default
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - default
    
networks:
  caddy_proxy:
    external: true
  default:
    driver: bridge
