
services:
  portainer:
    image: portainer/portainer-ce:2.42.0@sha256:c3c919ec68d130cbcb837693420592b91afd320b28b492c16c84ec5561bbf095
    container_name: portainer
    restart: always
    networks:
      - caddy_proxy
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

networks:
  caddy_proxy:
    external: true
  