
services:
  portainer:
    image: portainer/portainer-ce:2.45.0@sha256:efdd92144178ac25aa211bb35277157d97301c3734d22e50b64cf9f76674fcee
    container_name: portainer
    restart: always
    networks:
      - caddy_proxy
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

networks:
  caddy_proxy:
    external: true
  